### PR TITLE
feat: psp

### PR DESCRIPTION
**Pull request by graza-io**

### CODE REVIEW

**Comment by misraved** [comment]
Hey @graza-io, the changes look simple and good to me 👍 . Thanks for raising this PR 👍. 

However, the formatting looks a bit weird. I think we have additional tabs in the code. Could you please fix it?

@bigdatasourav could you please try this out from your end once so we can merge this in?

**Review by misraved — APPROVED** [review]

**Comment by graza-io** [comment]
> However, the formatting looks a bit weird. I think we have additional tabs in the code. Could you please fix it?

You're right, my pre-commit hook for `go fmt` seems to have been failing - manually done https://github.com/turbot/uptimerobotapi/pull/3/commits/c3ab3ebde595435ae95554897903c832996a0024 - apologies.

**Comment by misraved** [comment]
Thanks @graza-io for making the changes so promptly 👍 .

**Comment by misraved** [comment]
> > However, the formatting looks a bit weird. I think we have additional tabs in the code. Could you please fix it?
> 
> You're right, my pre-commit hook for `go fmt` seems to have been failing - manually done [c3ab3eb](https://github.com/turbot/uptimerobotapi/commit/c3ab3ebde595435ae95554897903c832996a0024) - apologies.

Hey @graza-io, I think we would also need a formatting update to the `psp.go` file.

**Comment by graza-io** [comment]
> Hey @graza-io, I think we would also need a formatting update to the `psp.go` file.

I believe that's in the commit mentioned, `client.go` & `psp.go`

**Comment by graza-io** [comment]
@bigdatasourav any feedback?

**Comment by bigdatasourav** [comment]
Looks good to me.

**Review by bigdatasourav — APPROVED** [review]

**Pull request merged**
